# docker-compose
version: '3.9'
services:
  nodejs:
    container_name: 'frontend-angular-17'
    build:
      context: .
      args:
        - CONFIG=production
        - BASE_URL=/
    restart: always
    ports:
      - 4000:4000
