# docker-compose
version: '3.9'
services:
  frontend:
    container_name: 'angular_and_nginx'
    build:
      context: .
      args:
        - CONFIG=production
        - BASE_URL=/
    restart: always
    ports:
      - 4000:4000
      - 443:4000
