# docker-compose
version: '3.9'
services:
  angular_and_nginx:
    container_name: 'angular_and_nginx'
    build:
      context: .
      args:
        - CONFIG=production
        - BASE_URL=/
    restart: always
    ports:
      - 80:4000
  php:
    container_name: 'php_server'
    build: /home/md-mailme-app/
    ports:
      - 8001:8001
    volumes:
      - /home/md-mailme-app/
