# docker-compose
version: '3.9'
services:
  md-website:
    container_name: 'md-website'
    build:
      context: .
      args:
        - CONFIG=production
        - BASE_URL=/
    restart: always
    ports:
      - 80:4000
  md-mailme-app:
    container_name: 'md-mailme'
    build: /home/md-mailme-app/
    ports:
      - 8001:8001
    volumes:
      - /home/md-mailme-app/
